osx_image: xcode8.2
language: objective-c
install:
- gem install cocoapods -v 1.2.0 --no-document

before_script:
- cd Example
- pod install

script:
- xcodebuild -workspace PopupCollectionViewController.xcworkspace -scheme "PopupCollectionViewControllerExample" -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s' build test | xcpretty